service: randy-pitcher-workspace--file-loader

frameworkVersion: '3'

plugins:
  - serverless-better-credentials

provider:
  name: aws
  runtime: python3.9

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every hour
      - schedule: rate(60 minute)
