# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "3"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_NUM_PARTITIONS=40

  kafka_connect:
    image: docker.io/bitnami/kafka:3.5
    container_name: kafka_connect
    volumes:
      - './tabular-sink/:/bitnami'
    depends_on:
      - kafka
    environment:
      - KAFKA_HEAP_OPTS=-Xmx16g
    command: connect-distributed.sh /bitnami/connect-distributed.properties

  kc_setup:
    image: docker.io/bitnami/kafka:3.5
    depends_on:
      - kafka_connect
    restart: "no"
    volumes:
      - './tabular-sink/:/bitnami'
    entrypoint: [ "bash", "-c", "sleep 10 && curl --request POST --url http://kafka_connect:8083/connectors --header 'Content-Type: application/json' --data-binary '@/bitnami/tabular-sink.json'"]

  shadowtraffic:
    image: shadowtraffic/shadowtraffic:0.0.6
    container_name: shadowtraffic
    env_file:
      - ./shadowtraffic/license.env
    volumes:
      - ./shadowtraffic/config.json:/home/config.json
    command: ["--config", "/home/config.json"]
    depends_on: 
      - kafka

volumes:
  kafka_data:
    driver: local